### ISSUE TITLE
Cloud II Wireless

### ISSUE THREAD

**Issue by michalis97500** [CubE135/hyperx-cloud-flight-s-battery-monitor#1]
Hey, I have a pair of Cloud II Wireless and would love to use this software. Is there a way to figure out what bytes I need to send to my device to get the same reply?

**Comment by CubE135** [comment]
Hi :)
I dont know if there is a way to read those values.
I found them online, in some Repository or Forum. If you find those values for your Headset Model, you might be able to fork this repo and use it for your model.
